#GRPC Backend python

apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-backend-deployment
  namespace: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpc-backend
      tier: backend
      version: v1
  template:
    metadata:
      labels:
        app: grpc-backend
        tier: backend
        version: v1
    spec:
      containers:
      - name: grpc-backend-pod
        image: yuriykrasilnikov/grpc_greeter_server:v.0.1.0
        env: 
          - name: cassandra-user
            value: admin
          - name: cassandra-password
            value: password
        ports:
        - name: grpc-port
          containerPort: 9000
        volumeMounts:
        - name: grpc-backend-storage
          mountPath: /usr/src/app
      volumes:
      - name: grpc-backend-storage
        hostPath:
          path: /minikube-host/grpc_greeter_server/src/
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: grpc-backend-service
  namespace: development
  labels:
    app: grpc-backend
    tier: backend
spec:
  type: NodePort
  selector:
    app: grpc-backend
  ports:
  - name: grpc-web-port
    port: 9000
    

