#GRPC Backend python

apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-backend-deployment
  namespace: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpc-backend-containers
      tier: backend
  template:
    metadata:
      labels:
        app: grpc-backend-containers
        tier: backend
    spec:
      containers:
      - name: grpc-backend-pod
        image: grpc_greeter_server:0.1.0
        imagePullPolicy: Never 
        ports:
        - name: grpc-port
          containerPort: 9000
        volumeMounts:
        - name: grpc-backend-storage
          mountPath: /usr/src/app
      volumes:
      - name: grpc-backend-storage
        hostPath:
          path: /minikube-host/grpc_greeter_server/src/
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: grpc-backend-service
  namespace: development
  labels:
    app: grpc-backend-service
    tier: backend
spec:
  type: NodePort
  selector:
    app: grpc-backend-containers
  ports:
  - name: grpc-web-port
    protocol: TCP
    port: 9000
  - name: metrics
    port: 9001


