#Backend python

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: envoy-deployment
  namespace: development
spec:
  replicas: 1
  serviceName: envoy-service
  selector:
    matchLabels:
      app: envoy-containers
      tier: backend
  template:
    metadata:
      labels:
        app: envoy-containers
        tier: backend
    spec:
      containers:
      - name: envoy-pod
        image: envoyproxy/envoy:v1.14.4
        ports:
        - containerPort: 8080
          name: envoy-port
        volumeMounts:
        - name: envoy-storage
          mountPath: /etc/envoy/
      volumes:
      - name: envoy-storage
        hostPath:
          path: /minikube-host/StartupAcademy/otusArch/envoy-proxy/

---
apiVersion: v1
kind: Service
metadata:
  name: envoy-service
  namespace: development
  labels:
    app: envoy-proxy
    tier: backend
spec:
  type: NodePort
  selector:
    app: envoy-containers
  ports:
  - name: envoy-port
    protocol: TCP
    port: 8080 #тук тук
    nodePort: 30009
    targetPort: 8080
  - name: metrics
    port: 9999


---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: envoy-service-monitoring
  namespace: monitoring
  labels:
    prometheus: kube-prometheus
    app: envoy-proxy
    tier: backend
spec:
  selector:
    matchLabels:
      app: envoy-proxy
  namespaceSelector:
    matchNames:
    - development
  endpoints:
  - port: metrics
    path: /stats/prometheus
    scheme: http
    interval: 60s