#Frontend react

apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-deployment
  namespace: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-frontend-containers
      tier: frontend
      version: v1
  template:
    metadata:
      labels:
        app: react-frontend-containers
        tier: frontend
        version: v1
    spec:
      containers:
      - name: react-pod
        image: grpc_react_client:0.1.0
        imagePullPolicy: Never 
        stdin: true
        tty: true
        ports:
        - name: frontend-port
          containerPort: 3000
        volumeMounts:
        - name: frontend-src-storage
          mountPath: /usr/frontend/src
        - name: frontend-public-storage
          mountPath: /usr/frontend/public
      volumes:
      - name: frontend-src-storage
        hostPath:
          path: /minikube-host/grpc_react_client/src/
      - name: frontend-public-storage
        hostPath:
          path: /minikube-host/grpc_react_client/public/

---
apiVersion: v1
kind: Service
metadata:
  name: react-service
  namespace: development
  labels:
    app: react-frontend
    tier: frontend
spec:
  type: NodePort
  selector:
    app: react-frontend-containers
  ports:
  - name: http-port
    port: 3000
  - name: metrics
    port: 9002
