apiVersion: apps/v1
kind: Deployment
metadata:
  name: command-saga
  namespace: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: command-saga
      tier: backend
      version: v1
  template:
    metadata:
      labels:
        app: command-saga
        tier: backend
        version: v1
    spec:
      containers:
      - name: command-saga
        image: yuriykrasilnikov/backend_saga:v.0.1.0
        imagePullPolicy: Always
        env: 
          - name: kafka-consumer-address
            value: "command-kafka.kafka.svc.cluster.local"
          - name: kafka-consumer-port
            value: "9092"
          - name: kafka-producer-address
            value: "command-kafka-0.command-kafka-headless.kafka.svc.cluster.local"
          - name: kafka-producer-port
            value: "9092"
        ports:
        - name: grpc-web-port
          containerPort: 9000
        volumeMounts:
        - name: saga-storage
          mountPath: /usr/src/app
      volumes:
      - name: saga-storage
        hostPath:
          path: /minikube-host/backend/saga/src
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: command-saga
  namespace: backend
  labels:
    app: command-saga
    tier: backend
spec:
  type: NodePort
  selector:
    app: command-saga
  ports:
  - name: grpc-web-port
    port: 9000
    

