{
 "title": "otusArch",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Cassandra Stats",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "cassandra_stats" }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{namespace=\"development\"}) by (pod)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "scalar(kube_resourcequota{namespace=\"development\", type=\"hard\",resource=\"requests.cpu\"})",
     "legendFormat": "quota - requests"
    },
    {
     "expr": "scalar(kube_resourcequota{namespace=\"development\", type=\"hard\",resource=\"limits.cpu\"})",
     "legendFormat": "quota - limits"
    }
   ]
  },
  {
   "title": "Memory Usage (w/o cache)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"development\", container!=\"\", image!=\"\"}) by (pod)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "scalar(kube_resourcequota{namespace=\"development\", type=\"hard\",resource=\"requests.memory\"})",
     "legendFormat": "quota - requests"
    },
    {
     "expr": "scalar(kube_resourcequota{namespace=\"development\", type=\"hard\",resource=\"limits.memory\"})",
     "legendFormat": "quota - limits"
    }
   ]
  },
  {
   "title": "Backend Latency (response time)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le, pod) (rate(grpc_server_handled_latency_seconds_bucket[5m]))) * 1000",
     "legendFormat": "{{pod}} Latency 0.5"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le, pod) (rate(grpc_server_handled_latency_seconds_bucket[5m]))) * 1000",
     "legendFormat": "{{pod}} Latency 0.95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le, pod) (rate(grpc_server_handled_latency_seconds_bucket[5m]))) * 1000",
     "legendFormat": "{{pod}} Latency 0.99"
    },
    {
     "expr": "histogram_quantile(1, sum by (le, pod) (rate(grpc_server_handled_latency_seconds_bucket[5m]))) * 1000",
     "legendFormat": "{{pod}} Latency 1"
    }
   ]
  },
  {
   "title": "Envoe Latency (response time)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le, pod) (rate(envoy_cluster_external_upstream_rq_time_bucket{envoy_cluster_name=\"greeter_service\"}[5m])))",
     "legendFormat": "{{pod}} Latency 0.5"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le, pod) (rate(envoy_cluster_external_upstream_rq_time_bucket{envoy_cluster_name=\"greeter_service\"}[5m])))",
     "legendFormat": "{{pod}} Latency 0.95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le, pod) (rate(envoy_cluster_external_upstream_rq_time_bucket{envoy_cluster_name=\"greeter_service\"}[5m])))",
     "legendFormat": "{{pod}} Latency 0.99"
    },
    {
     "expr": "histogram_quantile(1, sum by (le, pod) (rate(envoy_cluster_external_upstream_rq_time_bucket{envoy_cluster_name=\"greeter_service\"}[5m])))",
     "legendFormat": "{{pod}} Latency 1"
    }
   ]
  },
  {
   "title": "Backend Error Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (increase(grpc_server_handled_total{code!=\"OK\"}[5m]))",
     "legendFormat": "{{pod}} Error Rate"
    }
   ]
  },
  {
   "title": "Backend RPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (rate(grpc_server_handled_total[5m]))",
     "legendFormat": "{{pod}} RPC"
    }
   ]
  },
  {
   "title": "Envoe RPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (rate(envoy_cluster_upstream_rq_total{envoy_cluster_name=\"greeter_service\"}[5m]))",
     "legendFormat": "{{pod}} RPC"
    }
   ]
  },
  {
   "title": "Envoe Error Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (increase(envoy_cluster_external_upstream_rq{ envoy_cluster_name=\"greeter_service\", envoy_response_code!~\"2.*\"}[5m]))",
     "legendFormat": "Error Rate"
    }
   ]
  }
 ]
}