# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto.command.web_client import command_webclient_pb2 as proto_dot_command_dot_web__client_dot_command__webclient__pb2


class ProfileStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Insert = channel.unary_stream(
                '/api.command.webclient.v1.Profile/Insert',
                request_serializer=proto_dot_command_dot_web__client_dot_command__webclient__pb2.ProfileData.SerializeToString,
                response_deserializer=proto_dot_command_dot_web__client_dot_command__webclient__pb2.StatusResponse.FromString,
                )
        self.Update = channel.unary_stream(
                '/api.command.webclient.v1.Profile/Update',
                request_serializer=proto_dot_command_dot_web__client_dot_command__webclient__pb2.ProfileData.SerializeToString,
                response_deserializer=proto_dot_command_dot_web__client_dot_command__webclient__pb2.StatusResponse.FromString,
                )
        self.Remove = channel.unary_stream(
                '/api.command.webclient.v1.Profile/Remove',
                request_serializer=proto_dot_command_dot_web__client_dot_command__webclient__pb2.ProfileData.SerializeToString,
                response_deserializer=proto_dot_command_dot_web__client_dot_command__webclient__pb2.StatusResponse.FromString,
                )


class ProfileServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Insert(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Update(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Remove(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProfileServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Insert': grpc.unary_stream_rpc_method_handler(
                    servicer.Insert,
                    request_deserializer=proto_dot_command_dot_web__client_dot_command__webclient__pb2.ProfileData.FromString,
                    response_serializer=proto_dot_command_dot_web__client_dot_command__webclient__pb2.StatusResponse.SerializeToString,
            ),
            'Update': grpc.unary_stream_rpc_method_handler(
                    servicer.Update,
                    request_deserializer=proto_dot_command_dot_web__client_dot_command__webclient__pb2.ProfileData.FromString,
                    response_serializer=proto_dot_command_dot_web__client_dot_command__webclient__pb2.StatusResponse.SerializeToString,
            ),
            'Remove': grpc.unary_stream_rpc_method_handler(
                    servicer.Remove,
                    request_deserializer=proto_dot_command_dot_web__client_dot_command__webclient__pb2.ProfileData.FromString,
                    response_serializer=proto_dot_command_dot_web__client_dot_command__webclient__pb2.StatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'api.command.webclient.v1.Profile', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Profile(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Insert(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/api.command.webclient.v1.Profile/Insert',
            proto_dot_command_dot_web__client_dot_command__webclient__pb2.ProfileData.SerializeToString,
            proto_dot_command_dot_web__client_dot_command__webclient__pb2.StatusResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/api.command.webclient.v1.Profile/Update',
            proto_dot_command_dot_web__client_dot_command__webclient__pb2.ProfileData.SerializeToString,
            proto_dot_command_dot_web__client_dot_command__webclient__pb2.StatusResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Remove(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/api.command.webclient.v1.Profile/Remove',
            proto_dot_command_dot_web__client_dot_command__webclient__pb2.ProfileData.SerializeToString,
            proto_dot_command_dot_web__client_dot_command__webclient__pb2.StatusResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class BillingStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Insert = channel.unary_stream(
                '/api.command.webclient.v1.Billing/Insert',
                request_serializer=proto_dot_command_dot_web__client_dot_command__webclient__pb2.PaidData.SerializeToString,
                response_deserializer=proto_dot_command_dot_web__client_dot_command__webclient__pb2.StatusResponse.FromString,
                )


class BillingServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Insert(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BillingServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Insert': grpc.unary_stream_rpc_method_handler(
                    servicer.Insert,
                    request_deserializer=proto_dot_command_dot_web__client_dot_command__webclient__pb2.PaidData.FromString,
                    response_serializer=proto_dot_command_dot_web__client_dot_command__webclient__pb2.StatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'api.command.webclient.v1.Billing', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Billing(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Insert(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/api.command.webclient.v1.Billing/Insert',
            proto_dot_command_dot_web__client_dot_command__webclient__pb2.PaidData.SerializeToString,
            proto_dot_command_dot_web__client_dot_command__webclient__pb2.StatusResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
