# Default values for otus-arch.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: yuriykrasilnikov/otus-arch
  tag: v2

service:
  type: NodePort
  port: 9000

postgresql:
  enabled: true
  postgresqlUsername: yuriykrasilnikov
  postgresqlPassword: passwd
  postgresqlDatabase: otus-arch-data
  service:
    port: "5432"

secrete:
  name: otus-arch-secret

config:
  name: otus-arch-config

host:
  name: arch.homework
  path: /otusapp/yuriy-krasilnikov
