apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "otus-arch-chart.fullname" . }}
  labels:
    {{- include "otus-arch-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "otus-arch-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "otus-arch-chart.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          env:
            - name: DATABASE_URI
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrete.name }}
                  key: DATABASE_URI
            - name: GREETING
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.config.name }}
                  key: GREETING
          # livenessProbe:
          #   httpGet:
          #     port: http
          #     path: /
          #   initialDelaySeconds: 10
          #   periodSeconds: 5
          #   timeoutSeconds: 2
          # readinessProbe:
          #   httpGet:
          #     port: http
          #     path: /health
          #   initialDelaySeconds: 10
          #   periodSeconds: 5
