apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  profile: default

  components:
    base: # Базовые настройки. Роли, сервисы, CRD
      enabled: true

    istiodRemote: # Настройки, при которых уровень управления установлен вне кластера
      enabled: false

    ingressGateways: # Общая точка для входа трафика в Service mesh
    - name: istio-ingressgateway
      enabled: true
    
    egressGateways: # Общаая точка для выхода трафика из Service mesh
    - name: istio-egressgateway
      enabled: true
    
    pilot: # Управление конфигурацией proxy
      enabled: true

    # не работает
    cni: # Istio container network interface плагин, обеспечивает настройку сети POD
      enabled: true
      namespace: kube-system
  
  # Настройки Service mesh
  meshConfig:
    enableAutoMtls: true # Шифрование
    enableTracing: true # Включаем tracing
    enablePrometheusMerge: true 
    accessLogFile: /dev/stdout


  # Настройки компонентов
  values:

    pilot:
      autoscaleEnabled: false
      env:
        PILOT_ENABLE_VIRTUAL_SERVICE_DELEGATE: true

    gateways:
      istio-ingressgateway:
        autoscaleEnabled: false
      istio-egressgateway:
        autoscaleEnabled: false

    telemetry:
      v2:
        enabled: true
        prometheus:
          enabled: true
          configOverride:
            inboundSidecar:
              debug: false
              stat_prefix: istio
              metrics:
                - name: requests_total
                  dimensions:
                    destination_port: string(destination.port)
                    request_host: request.host
            outboundSidecar:
              debug: false
              stat_prefix: istio
              metrics:
                - name: requests_total
                  dimensions:
                    destination_port: string(destination.port)
                    request_host: request.host
            gateway:
              debug: false
              stat_prefix: istio
              disable_host_header_fallback: true
              metrics:
                - name: requests_total
                  dimensions:
                    destination_port: string(destination.port)
                    request_host: request.host

    
    sidecarInjectorWebhook:
      rewriteAppHTTPProbe: true
      enableNamespacesByDefault: true
      objectSelector:
        enabled: false
        autoInject: true

    cni:
      cniBinDir: /opt/cni/bin
      cniConfDir: /etc/cni/net.d
      excludeNamespaces:
      - istio-system
      - kube-system
      - kube-node-lease
      - kube-public
      logLevel: info
      repair:
        deletePods: false