apiVersion: apps/v1
kind: Deployment
metadata:
  name: query-webclient-orchestrator
  namespace: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: query-webclient-orchestrator
      tier: backend
      version: v1
  template:
    metadata:
      labels:
        app: query-webclient-orchestrator
        tier: backend
        version: v1
    spec:
      containers:
      - name: query-webclient-orchestrator
        image: yuriykrasilnikov/backend_orchestrator:v.0.1.0
        imagePullPolicy: Always
        env: 
          - name: profile-address
            value: "query-profiles"
          - name: profile-port
            value: "9000"
          - name: record-address
            value: "query-profiles"
          - name: record-port
            value: "9000"
        ports:
        - name: grpc-web-port
          containerPort: 9000
        volumeMounts:
        - name: orchestrator-storage
          mountPath: /usr/src/app
      volumes:
      - name: orchestrator-storage
        hostPath:
          path: /minikube-host/backend/orchestrator/src
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: query-webclient-orchestrator
  namespace: backend
  labels:
    app: query-webclient-orchestrator
    tier: backend
spec:
  type: NodePort
  selector:
    app: query-webclient-orchestrator
  ports:
  - name: grpc-web-port
    port: 9000
    

