apiVersion: apps/v1
kind: Deployment
metadata:
  name: query-charts
  namespace: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: query-charts
      tier: backend
      version: v1
  template:
    metadata:
      labels:
        app: query-charts
        tier: backend
        version: v1
    spec:
      containers:
      - name: query-charts
        image: yuriykrasilnikov/backend_query_charts:v.0.1.0
        imagePullPolicy: Always
        env: 
          - name: db-address
            value: "dbcharts-mongodb.database.svc.cluster.local"
          - name: db-port
            value: "27017"
          - name: db-name
            value: "charts"
          - name: db-user
            value: "mongo"
          - name: db-password
            value: "password"
        ports:
        - name: grpc-port
          containerPort: 9000
        volumeMounts:
        - name: query-charts-storage
          mountPath: /usr/src/app
      volumes:
      - name: query-charts-storage
        hostPath:
          path: /minikube-host/backend/query/charts/src
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: query-charts
  namespace: backend
  labels:
    app: query-charts
    tier: backend
spec:
  type: NodePort
  selector:
    app: query-charts
  ports:
  - name: grpc-port
    port: 9000
    

