# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto.web_client import web_client_pb2 as proto_dot_web__client_dot_web__client__pb2


class ProfileStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Get = channel.unary_unary(
                '/api.web_client.Profile/Get',
                request_serializer=proto_dot_web__client_dot_web__client__pb2.ProfileRequest.SerializeToString,
                response_deserializer=proto_dot_web__client_dot_web__client__pb2.ProfileResponse.FromString,
                )
        self.Insert = channel.unary_unary(
                '/api.web_client.Profile/Insert',
                request_serializer=proto_dot_web__client_dot_web__client__pb2.UpdateProfileRequest.SerializeToString,
                response_deserializer=proto_dot_web__client_dot_web__client__pb2.ProfileResponse.FromString,
                )
        self.Update = channel.unary_unary(
                '/api.web_client.Profile/Update',
                request_serializer=proto_dot_web__client_dot_web__client__pb2.UpdateProfileRequest.SerializeToString,
                response_deserializer=proto_dot_web__client_dot_web__client__pb2.ProfileResponse.FromString,
                )
        self.Remove = channel.unary_unary(
                '/api.web_client.Profile/Remove',
                request_serializer=proto_dot_web__client_dot_web__client__pb2.ProfileRequest.SerializeToString,
                response_deserializer=proto_dot_web__client_dot_web__client__pb2.Empty.FromString,
                )
        self.Registration = channel.unary_unary(
                '/api.web_client.Profile/Registration',
                request_serializer=proto_dot_web__client_dot_web__client__pb2.RegistrationRequest.SerializeToString,
                response_deserializer=proto_dot_web__client_dot_web__client__pb2.Empty.FromString,
                )


class ProfileServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Insert(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Update(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Remove(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Registration(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProfileServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=proto_dot_web__client_dot_web__client__pb2.ProfileRequest.FromString,
                    response_serializer=proto_dot_web__client_dot_web__client__pb2.ProfileResponse.SerializeToString,
            ),
            'Insert': grpc.unary_unary_rpc_method_handler(
                    servicer.Insert,
                    request_deserializer=proto_dot_web__client_dot_web__client__pb2.UpdateProfileRequest.FromString,
                    response_serializer=proto_dot_web__client_dot_web__client__pb2.ProfileResponse.SerializeToString,
            ),
            'Update': grpc.unary_unary_rpc_method_handler(
                    servicer.Update,
                    request_deserializer=proto_dot_web__client_dot_web__client__pb2.UpdateProfileRequest.FromString,
                    response_serializer=proto_dot_web__client_dot_web__client__pb2.ProfileResponse.SerializeToString,
            ),
            'Remove': grpc.unary_unary_rpc_method_handler(
                    servicer.Remove,
                    request_deserializer=proto_dot_web__client_dot_web__client__pb2.ProfileRequest.FromString,
                    response_serializer=proto_dot_web__client_dot_web__client__pb2.Empty.SerializeToString,
            ),
            'Registration': grpc.unary_unary_rpc_method_handler(
                    servicer.Registration,
                    request_deserializer=proto_dot_web__client_dot_web__client__pb2.RegistrationRequest.FromString,
                    response_serializer=proto_dot_web__client_dot_web__client__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'api.web_client.Profile', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Profile(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.web_client.Profile/Get',
            proto_dot_web__client_dot_web__client__pb2.ProfileRequest.SerializeToString,
            proto_dot_web__client_dot_web__client__pb2.ProfileResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Insert(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.web_client.Profile/Insert',
            proto_dot_web__client_dot_web__client__pb2.UpdateProfileRequest.SerializeToString,
            proto_dot_web__client_dot_web__client__pb2.ProfileResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.web_client.Profile/Update',
            proto_dot_web__client_dot_web__client__pb2.UpdateProfileRequest.SerializeToString,
            proto_dot_web__client_dot_web__client__pb2.ProfileResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Remove(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.web_client.Profile/Remove',
            proto_dot_web__client_dot_web__client__pb2.ProfileRequest.SerializeToString,
            proto_dot_web__client_dot_web__client__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Registration(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.web_client.Profile/Registration',
            proto_dot_web__client_dot_web__client__pb2.RegistrationRequest.SerializeToString,
            proto_dot_web__client_dot_web__client__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
