apiVersion: v1
kind: Namespace
metadata:
  name: development
  labels:
    name: development
    app: ykrasilnikov-app
    istio-injection: enabled # Включаем инжект сайдкаров Istio для неймспейса

---
apiVersion: v1
kind: Namespace
metadata:
  name: cassandra
  labels:
    name: cassandra
    app: ykrasilnikov-app
    istio-injection: enabled # Включаем инжект сайдкаров Istio для неймспейса