apiVersion: v1
kind: Namespace
metadata:
  name: development
  labels:
    name: development
    app: ykrasilnikov-app

---
apiVersion: v1
kind: Namespace
metadata:
  name: staging 
  labels:
    name: staging
    app: ykrasilnikov-app

---
apiVersion: v1
kind: Namespace
metadata:
  name: production
  labels:
    name: production
    app: ykrasilnikov-app

---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    name: monitoring
    app: ykrasilnikov-app

---
apiVersion: v1
kind: Namespace
metadata:
  name: cassandra
  labels:
    name: cassandra
    app: ykrasilnikov-app