apiVersion: v1
kind: Namespace
metadata:
  name: frontend
  labels:
    name: frontend

---
apiVersion: v1
kind: Namespace
metadata:
  name: backend
  labels:
    name: backend

---
apiVersion: v1
kind: Namespace
metadata:
  name: authorization 
  labels:
    name: authorization

---
apiVersion: v1
kind: Namespace
metadata:
  name: database 
  labels:
    name: database

---
apiVersion: v1
kind: Namespace
metadata:
  name: kafka 
  labels:
    name: kafka

    
