apiVersion: v1
kind: Namespace
metadata:
  name: development
  labels:
    name: development
    app: ykrasilnikov-app
  

---
apiVersion: v1
kind: Namespace
metadata:
  name: cassandra
  labels:
    name: cassandra
    app: ykrasilnikov-app

---
apiVersion: v1
kind: Namespace
metadata:
  name: oauth2
  labels:
    name: oauth2
    app: ykrasilnikov-app
    
