# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto import api_demo_pb2 as proto_dot_api__demo__pb2


class GreeterStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SayHello = channel.unary_unary(
                '/api.demo.Greeter/SayHello',
                request_serializer=proto_dot_api__demo__pb2.HelloRequest.SerializeToString,
                response_deserializer=proto_dot_api__demo__pb2.HelloReply.FromString,
                )
        self.SayRepeatHello = channel.unary_stream(
                '/api.demo.Greeter/SayRepeatHello',
                request_serializer=proto_dot_api__demo__pb2.RepeatHelloRequest.SerializeToString,
                response_deserializer=proto_dot_api__demo__pb2.HelloReply.FromString,
                )


class GreeterServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SayHello(self, request, context):
        """unary call
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SayRepeatHello(self, request, context):
        """server response-streaming RPC call
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GreeterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SayHello': grpc.unary_unary_rpc_method_handler(
                    servicer.SayHello,
                    request_deserializer=proto_dot_api__demo__pb2.HelloRequest.FromString,
                    response_serializer=proto_dot_api__demo__pb2.HelloReply.SerializeToString,
            ),
            'SayRepeatHello': grpc.unary_stream_rpc_method_handler(
                    servicer.SayRepeatHello,
                    request_deserializer=proto_dot_api__demo__pb2.RepeatHelloRequest.FromString,
                    response_serializer=proto_dot_api__demo__pb2.HelloReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'api.demo.Greeter', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Greeter(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SayHello(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.demo.Greeter/SayHello',
            proto_dot_api__demo__pb2.HelloRequest.SerializeToString,
            proto_dot_api__demo__pb2.HelloReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SayRepeatHello(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/api.demo.Greeter/SayRepeatHello',
            proto_dot_api__demo__pb2.RepeatHelloRequest.SerializeToString,
            proto_dot_api__demo__pb2.HelloReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
