# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from proto.query.web_client import query_webclient_pb2 as proto_dot_query_dot_web__client_dot_query__webclient__pb2


class ProfileStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Get = channel.unary_unary(
                '/api.query.webclient.v1.Profile/Get',
                request_serializer=proto_dot_query_dot_web__client_dot_query__webclient__pb2.ProfilesRequest.SerializeToString,
                response_deserializer=proto_dot_query_dot_web__client_dot_query__webclient__pb2.ProfileDataList.FromString,
                )
        self.Identification = channel.unary_unary(
                '/api.query.webclient.v1.Profile/Identification',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=proto_dot_query_dot_web__client_dot_query__webclient__pb2.ProfileData.FromString,
                )


class ProfileServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Identification(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProfileServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=proto_dot_query_dot_web__client_dot_query__webclient__pb2.ProfilesRequest.FromString,
                    response_serializer=proto_dot_query_dot_web__client_dot_query__webclient__pb2.ProfileDataList.SerializeToString,
            ),
            'Identification': grpc.unary_unary_rpc_method_handler(
                    servicer.Identification,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=proto_dot_query_dot_web__client_dot_query__webclient__pb2.ProfileData.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'api.query.webclient.v1.Profile', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Profile(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.query.webclient.v1.Profile/Get',
            proto_dot_query_dot_web__client_dot_query__webclient__pb2.ProfilesRequest.SerializeToString,
            proto_dot_query_dot_web__client_dot_query__webclient__pb2.ProfileDataList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Identification(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.query.webclient.v1.Profile/Identification',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            proto_dot_query_dot_web__client_dot_query__webclient__pb2.ProfileData.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class RecordStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Get = channel.unary_unary(
                '/api.query.webclient.v1.Record/Get',
                request_serializer=proto_dot_query_dot_web__client_dot_query__webclient__pb2.RecordsPaginationRequest.SerializeToString,
                response_deserializer=proto_dot_query_dot_web__client_dot_query__webclient__pb2.RecordsCursorResponse.FromString,
                )


class RecordServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RecordServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=proto_dot_query_dot_web__client_dot_query__webclient__pb2.RecordsPaginationRequest.FromString,
                    response_serializer=proto_dot_query_dot_web__client_dot_query__webclient__pb2.RecordsCursorResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'api.query.webclient.v1.Record', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Record(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.query.webclient.v1.Record/Get',
            proto_dot_query_dot_web__client_dot_query__webclient__pb2.RecordsPaginationRequest.SerializeToString,
            proto_dot_query_dot_web__client_dot_query__webclient__pb2.RecordsCursorResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
