
securityContext:
  runAsUser: 0

master:
  persistence:
    enabled: true

slave:
  persistence:
    enabled: true
  livenessProbe:
    enabled: false
  readinessProbe:
    enabled: false

metrics:
  enabled: true

usePassword: true
password: 4JDvOM7Ou8ox


